// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "./_components/Header";
// import Footer from "./_components/Footer";
// import { CartProvider } from "./context/CartContext"; // Import the CartProvider

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
//       >
//         <CartProvider> {/* Wrap your entire app with CartProvider */}
//           <Header />
//           <main className="flex-grow">{children}</main> {/* Main content area */}
//           <Footer />
//         </CartProvider>
//       </body>
//     </html>
//   );
// }




import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { CartProvider } from "./context/CartContext"; // CartProvider import
import { AuthProvider } from "./context/AuthContext"; // Import the AuthProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <AuthProvider> {/* Wrap your entire app with AuthProvider */}
          <CartProvider> {/* Wrap the CartProvider around the AuthProvider */}
            <Header />
            <main className="flex-grow">{children}</main> {/* Main content area */}
            <Footer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}

